version: '3'
services:
  server:
    container_name: server
    image: server:latest
    entrypoint: python3 /main.py
    volumes:
      - ./config/server.ini:/config.ini
    environment:
      - PYTHONUNBUFFERED=1
      - SERVER_PORT=12345
      - SERVER_LISTEN_BACKLOG=7
      - LOGGING_LEVEL=DEBUG
    networks:
      - testing_net

  client1:
    container_name: client1
    image: client:latest
    entrypoint: /client
    volumes:
      - ./config/client.yaml:/config.yaml
    environment:
      - CLI_ID=1
      - CLI_SERVER_ADDRESS=server:12345
      - CLI_LOG_LEVEL=DEBUG
      - DOCUMENT=19700101
      - FIRST_NAME=Mr
      - LAST_NAME=Epoch
      - BIRTH_DATE=1970-01-01
    networks:
      - testing_net
    depends_on:
      - server

  client2:
    container_name: client2
    image: client:latest
    entrypoint: /client
    volumes:
      - ./config/client.yaml:/config.yaml
    environment:
      - CLI_ID=2
      - CLI_SERVER_ADDRESS=server:12345
      - CLI_LOG_LEVEL=DEBUG
      - DOCUMENT=19700101
      - FIRST_NAME=Mr
      - LAST_NAME=Epoch
      - BIRTH_DATE=1970-01-01
    networks:
      - testing_net
    depends_on:
      - server
networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
